# Generated by Django 3.2.8 on 2021-10-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='test',
            new_name='text',
        ),
    ]
